spring:
  application:
    name: post
  datasource:
    url: jdbc:postgresql://localhost:5432/post
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: post
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: post
server:
  port: 8089
logging:
  level:
    org:
      flywaydb: DEBUG
      springframework:
        web: DEBUG
  practical:
    post: TRACE
