CREATE TABLE users(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    email varchar(100) not null unique,
    username varchar(100) not null unique,
    password varchar,
    created timestamp not null default current_timestamp,
    updated timestamp not null default current_timestamp,
    deleted bool not null DEFAULT FALSE,
    registration_status varchar not null,
    last_login timestamp
);

CREATE TABLE post(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT references users(id) on delete cascade not null,
    title varchar not null unique,
    content text not null,
    created timestamp NOT NULL DEFAULT current_timestamp,
    updated timestamp NOT NULL DEFAULT current_timestamp,
    deleted bool NOT NULL DEFAULT FALSE
);

CREATE TABLE role(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar not null unique,
    user_system_role varchar not null,
    active bool not null default true,
    created_by varchar
);

CREATE TABLE user_role(
    user_id int references users(id) on delete cascade not null,
    role_id int references role(id) on delete cascade not null,
    primary key(user_id, role_id)
);

INSERT INTO role(name, user_system_role, created_by) values('SUPER_ADMIN', 'SUPER_ADMIN', 'SUPER_ADMIN'),
    ('ADMIN', 'ADMIN', 'SUPER_ADMIN'),
    ('USER', 'USER', 'SUPER_ADMIN');