CREATE TABLE comment(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT references users(id) on delete cascade not null,
    post_id INT references post(id) on delete cascade not null,
    content text not null,
    created timestamp NOT NULL DEFAULT current_timestamp,
    updated timestamp NOT NULL DEFAULT current_timestamp,
    deleted bool NOT NULL DEFAULT FALSE,
    created_by varchar
);

CREATE INDEX idk_comment_user_id ON comment(user_id);
CREATE INDEX idk_comment_post_id ON comment(post_id);

